[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
Stablecoin = "AXtZmZ41Eq7NusPoEbFw2k4haaXHQxBrCrcg4y1oW7Eh"

[programs.devnet]
Stablecoin = "AXtZmZ41Eq7NusPoEbFw2k4haaXHQxBrCrcg4y1oW7Eh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cd .. && npm run test:anchor"
